spring.application.name=ticketBooking
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_booking
spring.datasource.username=yashogale

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.docker.compose.enabled=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
